### PR TITLE
Add QPS API functionality for Qualys host asset tagging

### PR DESCRIPTION
**Pull request by pandackindley**
## Guidelines

No changes are made to existing functions of the module. There are only additions of functions and classes.

- Unreleased section of changelog updated to indicate new functions and classes added
- Approved PowerShell verbs are used for new functions
- Comment based help included in functions and classes
- Module version updated to 1.7.0
- Markdown documentation for new functions and classes in the docs folder

## Purpose

Several years ago, a number of engineers at UMN developed a PowerShell module for interacting with the Qualys vulnerability management API. After some time, UMN changed VMS vendors and handed off ownership of the existing module. Through much work and evolution, UofIQualys came to be. UMN has begun using Qualys again and will automate processes using UofIQualys.

UMN business processes require tagging assets to understand their context from a variety of perspectives. UMN tag contexts are defined by the tag category, for instance to distinguish a set of tags that defines the data classification from a set of tags defining the administrative unit that manages applications on the asset. To best delegate responsibility for remediation and distribution of reports, we duplicate a tagging structure in the Qualys asset management interface.

In order to accurately reflect the state of our assets in Qualys, we need to interact with the Qualys QPS API to perform tagging operations. The QPS API works differently than the 'main' Qualys API; basic authentication must be used for every request and XML-formatted request bodies are the norm. Thus, some new functionality needs to be added to a Qualys PowerShell module.

## Approach

This change introduces six new functions and two new classes to the UofIQualys module. The two classes are QualysAsset and QualysTag. These classes incorporate all information returned from the QPS API about the object, expanded into a PowerShell-native object. To import classes in the PowerShell module, we add a block to the PSM1 file that recursively imports PS1 files from the  .\Classes\ directory. The classes are stored in a single PS1 file for now to avoid circular dependency issues at import time. In order to take advantage of classes and asset tagging operations, the module should be imported with

```powershell
using module UofIQualys
```

instead of

```powershell
Import-Module UofIQualys
```

Existing automation using Import-Module will continue to have access to all the non-QPS functions as expected, but would need to be updated to access the new functions and classes.

The QualysAsset object is quite rich and includes nested custom object properties that retain the structure of the Qualys API response in a more accessible PowerShell object. There are additional properties intended to be user-supplied, including a vtags property intended to contain a list of custom objects with TagName and Category properties. An automation may supply appropriately formatted external tags from a source of truth (for instance, a virtualization platform, cloud provider, or asset inventory) for later synchronization.

The QualysTag object contains information about a tag from the QPS API, as well as optional ParentTag and ChildTags properties. This allows an automation to fetch a complete tree structure of tags within a single object, if desired.

There are three Get functions: Get-QualysAsset, Get-QualysTag, and Get-QualysAssetInventory. The first two return objects or lists of objects of QualysAsset and QualysTag respectively.  While the API requires many requests to use ID numbers of assets and tags, some work has been done to allow for searching by name, tag assignment, and parent tag. Get-QualysAssetInventory operates differently than Get-QualysAsset in order to retrieve an entire inventory of assets visible to the supplied credential, so is a separate function.

Three functions are introduced to support tagging operations: Add-QualysTagAssignment, Remove-QualysTagAssignment, and Sync-QualysTagAssignment. The first two are fairly self-explanatory and are used to add and remove tags from QualysAssets. These functions are used in a number of methods of the two new classes.

The Sync-QualysTagAssignment function requires some additional information from the invoker: the input QualysAsset(s) must have a list of source-of-truth tags in the vtags property, and the function requires a CategoryDefinitions hashtable input. The hashtable defines the list of categories with which the invoker wishes to sync tags to Qualys, and a list of acceptable tag names in that category. With this input, the function can detect and remove incorrect tags, add missing correct tags, and preserve tags which exist only in Qualys.

### CODE REVIEW

**Review by baristaTam — DISMISSED** [review]
Carter, thank you for this awesome contribution to our module! I'm so sorry for not getting back to you sooner. You can thank Mike for pinging me. :)

There are a few changes here that would need to be made before we approve. Could you please remove the inputQualysAPIUrl and inputCredential parameters from your functions, and instead of using invoke-webrequest, use Invoke-QualysRestCall following the pattern of the other functions in this module. If you need any help with that, please reach out to me at buch1@illinois.edu and I can set up a call to pair program with you. 

Please remove the .NOTES section of the comment based help. For authorship, your github contribution is proof of that. This is an open-source project by UofI and the branding should reflect that instead of individual names. For the notes about the best way to get a piece of information for a parameter, I think that would be better to include in the parameter description. 

This one is more nitpicky but if you could please also change the camelCase parameter names in the comment-based help to PascalCase it would look more consistent. 

Again, this is an excellent contribution. We do not make much use of tags in our management of Qualys, but of course they are a key part of the platform. We're excited to have tagging functions included in the module. Thank you! 
-Tamara Buch

**Comment by pandackindley** [comment]
Hey Tamara, thanks for the review! I should be able to implement those changes in short order. But I will have to take another look at using Invoke-QualysRestCall. I may require modifications to that to achieve compatibility with the QPS API, but will have a better idea what needs implementation tomorrow. My initial goal was to avoid modifying anything already working in the current module but if it makes sense to broaden compatibility, we can make it happen.

It was quite serendipitous to have been on a call with Mike today while thinking about this! Small world.

More soon!

**Comment by edthedev** [comment]
@pandackindley  Sorry for the delay reviewing this. I pulled this into our project board, so any future changes will get prompt consideration.

**Comment by edthedev** [comment]
> please reach out to me at [buch1@illinois.edu](mailto:buch1@illinois.edu) and I can set up a call to pair program with you.

@baristaTam This probably goes as given, but if we do go this route, I would be delighted to offer one of the existing scheduled ensemble rooms for this effort.

**Comment by pandackindley** [comment]
Thanks Edward! Tamara and I met yesterday to discuss the work that needs to be done to finish my additions. Turns out, the module assumes there is only one region/endpoint for the Qualys API. There are actually a number of regions (or "platforms" as Qualys calls them: [https://www.qualys.com/platform-identification/](https://www.qualys.com/platform-identification/) ), so module users will need a mechanism to specify their region and override what's currently provided in settings.json. For testing, I'm leaving it as is but it warrants discussion with everyone involved in the project.

Next week I should have time to implement the changes now that I understand the assumptions Invoke-QualysRestCall and settings.json make. Then we can sort out what to do about region context settings.

**Comment by pandackindley** [comment]
Alright, I went through and fixed camel case in the comment-based help and refactored my functions to use Invoke-QualysRestCall. I did have to modify Invoke-QualysRestCall to use parameter sets and switch behavior and acceptable input for $body (still a hashtable) vs. $XmlBody (string). If the XmlBody parameter set is used, we also add Content-Type and Accept headers to the IVRSplat in order to form a request that the QPS API recognizes as valid. If you could please validate my testing that existing uses of Invoke-QualysRestCall with hashtable bodies still function, I would appreciate it!

All the refactoring of my tagging functions and methods has been tested so I'm ready to ship this. I've updated the help docs as well to reflect the now standardized inputs for my functions. In order for this module to work, though, we need to tackle the issue of platform selection. I really don't want to have to manually go edit a settings.json file on my production automation workers every time a new one is deployed or the module gets updated. But I opened an issue for that based on what Tamara and I talked about last week, so we can work on that over there.

Let me know what you think and if you have any more change requests!

**Review by mpitcel — DISMISSED** [review]

**Review by edthedev — DISMISSED** [review]

**Comment by pandackindley** [comment]
Updated with some minor fixes for tests, and added environmental variable override of settings.json script-scoped variables. It was such a small change I decided to go ahead and include it in this PR.

**Review by edthedev — DISMISSED** [review]
@pandackindley Thanks for these updates! The changes look great. I've kicked off the test suite and it looks like SciptAnalyzer is looking for a type adjustment.

**Review by edthedev — APPROVED** [review]

**Comment by pandackindley** [comment]
Fixed the explicit type declarations!

**Comment by pandackindley** [comment]
I added a minor tweak to the environment variables check for overriding settings.json and added a couple lines to README.md explaining how to use this. This was done to accommodate loading the module with `using` - required for taking advantage of the new classes.

**Review by baristaTam — APPROVED** [review]

**Review by edthedev — APPROVED** [review]

**Pull request merged**
